# Generated by Django 4.2 on 2025-05-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ges_project_app', '0005_changerequest_remove_projectsconflits_conflit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrageSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_choice', models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
