# Generated by Django 4.2 on 2025-05-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ges_project_app', '0006_parametragesysteme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParametrageSysteme',
        ),
        migrations.AddField(
            model_name='deadline',
            name='level',
            field=models.CharField(choices=[('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='deadline',
            name='max_choice',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
